/* This file should be replaced by element header generated by
 * gst-element-maker, or by your own source code.  To generate suitable
 * element header using gst-element-maker, run:
 *
 *   gst-element-maker  perf BASE_CLASS
 *
 * Where BASE_CLASS is replaced by one of the base class templates,
 * such as basesrc, basetransform, audiofilter, videofilter2, etc.
 * Then copy the resulting gstperf.h file over this file, and
 * gstperf.c over gstperf.c.
 */
/* The rest of this file is shim code to allow the project to compile */
#define Ugst_TYPE_Uperf G_TYPE_NONE
